---
- hosts: localhost
  tasks:
    - name: Install git-review
      apt:
        name: git-review
        state: present
    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
    - name: Install python-pip
      apt:
        name: python-pip
        state: present
    - name: Install virtualenv
      apt:
        name: virtualenv 
        state: present
        #    - name: Install virtualenv
        #      pip:
        #        name: virtualenv
